### PR TITLE
account_lines request schema 

### PR DESCRIPTION
**Pull request by ckeshava**
OpenAPI and AsyncAPI models for `account_lines` request

### CODE REVIEW

**Comment by ckeshava** [comment]
`account_lines` request does not have difference between rippled API v1 and v2. I did not find any such differences mentioned in the [documentation](https://xrpl.org/docs/references/http-websocket-apis/public-api-methods/account-methods/account_lines)

I used the `typescript-axios` generator (with the OpenAPI generator project) to generator Typescript SDK. The `account_lines` related code appears to have been generated correctly.

**Comment by ckeshava** [comment]
P.S.: I filed an [issue report](https://github.com/XRPLF/xrpl-dev-portal/issues/2741) pertaining to `account_lines` request.

Once this bug report is addressed on the documentation website, we will need to update the specification.

**Review by pdp2121 — APPROVED** [review]
LGTM

**Comment by ckeshava** [comment]
@pdp2121 I'll create a separate PR for `ledger_entry` request. Can we merge this PR first?

**Pull request merged**
